language: cpp
dist: xenial

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install qtbase5-dev qtdeclarative5-dev libQt6webkit5-dev libsqlite3-dev
  - sudo apt-get install Qt6-default qttools5-dev-tools
os: linux
script:
  - cd Qt.Core
  - qmake -project
  - qmake Qt.Core.pro
  - make
  - cd ../Qt.Widgets
  - qmake -project
  - qmake Qt.Widgets.pro
  - make
  - cd ..
